// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_football/frameworks-and-drivers/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ClubHiveObjAdapter());
    registerAdapter(GameSlotHiveObjAdapter());
    registerAdapter(LeagueHiveObjAdapter());
    registerAdapter(NationAdapter());
    registerAdapter(SeasonHiveObjAdapter());
  }
}
